version: '3.8'

services:
  app:
    image: piyush923/myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NEXT_PUBLIC_ENV_BASE_PATH=http://localhost:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
