import PropTypes from 'prop-types';
import '@/assets/scss/styles.scss';
import Header from '@/components/Header';
import Providers from '@/redux/providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.string,
};
